package com.mikehelmick.proc;

import java.io.Serializable;

/**
 * Clock is a marker interface. You have to decide how to represent clocks in your system.
 * Do so by implementing this interface.
 * </p>
 * Since this interface extends {@link Comparable} you must provide a compareTo method. This will
 * ensure proper ordering of events generated by your code.
 */
public interface Clock extends Serializable, Comparable<Clock> {

  /**
   * Please override the toString method and provide something reasonable
   * since this is used in output.
   */
  public abstract String toString();
}
